[package]
name = "call-the-police-bot"
version = "1.2.0"
edition = "2021"

[[bin]]
name = "call-the-police-bot"
path = "src/main.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15"

opentelemetry = "0.23"
opentelemetry-otlp = { version = "0.16", features = ["http-proto", "grpc-tonic", "reqwest"] }
opentelemetry_sdk = { version = "0.23", features = ["rt-tokio"] }
opentelemetry-semantic-conventions = "0.15"
tracing = "0.1"
tracing-opentelemetry = "0.24"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }

teloxide = { version = "0.12", features = ["macros", "webhooks", "webhooks-axum"] }
reqwest = "0.11" # for teloxide
rand = "0.8"
anyhow = "1.0"
