[package]
name = "call-the-police-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15"

tracing = "0.1"
tracing-opentelemetry = "0.23"
tracing-subscriber = "0.3"

teloxide = { version = "0.12", features = ["macros"] }
reqwest = "0.12"
rand = "0.8"
